version: '3.4'

services:
  CatalogDB:
     image: postgres
  BasketDb:
     image: postgres

  destributedcache:
     image: redis
  OrdersDb:
     image: mcr.microsoft.com/mssql/server:2019-latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  Postgres_basket:
   



